const ecoleJSON =
 '{"intitule": "L\'école", "theme" : [{"mot":"cahier", "description":"Outil pour écolier."}, {"mot":"classe", "description":"Ensemble des personnes qui ont en commun une fonction."},{"mot":"apprendre", "description":"Acquérir par l\'étude, par la pratique, par l\'expérience une connaissance, un savoir-faire."},{"mot":"instituteur", "description":"Personne qui enseigne."},{"mot":"rentrée", "description":"Reprise des activités scolaires."},{"mot":"primaire", "description":"Qui est du premier degré."},{"mot":"directeur", "description":"Personne à la tête de l\'établissement"},{"mot":"note", "description":"Appréciation écrite."},{"mot":"collège", "description":"Établissement d\'enseignement"},{"mot":"modulo", "description":"Opération mathématique"}]}';

const paysagesClimatJSON = 
'{"intitule": "Paysages et Climat", "theme" : [{"mot":"neige","description":"Tombe dans les hautes régions de l\'atmosphère."}, {"mot":"pluie","description":"Ennuyeux comme la ..."}, {"mot":"vent","description":"Déplacement naturel de l\'atmosphère."}, {"mot":"doux","description":" Qui produit une sensation agréable au toucher."}, {"mot":"paysage","description":"Partie d\'un pays que la nature présente à un observateur."}, {"mot":"brouillard","description":"Phénomène naturel produit par de fines gouttelettes d\'eau."}, {"mot":"montagne","description":"Importante élévation de terrain."}, {"mot":"tremblement","description":"Secousses répétées qui agitent une chose."}, {"mot":"pente","description":"Inclinaison."}, {"mot":"inondation","description":"Grande quantité d\'eau qui se répand."}]}';

const calculMesuresJSON = 
'{"intitule": "Calcul et Mesures", "theme" : [{"mot":"deux","description":"Un chiffre."}, {"mot":"troiscents","description":"Un nombre."}, {"mot":"unité","description":"Dans les mesures."}, {"mot":"addition","description":"Opération mathématique."}, {"mot":"chiffre","description":"Un chiffre."}, {"mot":"prouver","description":"démontrer."}, {"mot":"reste","description":"Dans la division."}, {"mot":"diminuer","description":"décrémenter."}, {"mot":"balance","description":"Formé à l\'origine d\'une tige mobile et de plateaux."}, {"mot":"quarante","description":"Un nombre."}]}';

const alimentsJSON = 
'{"intitule": "Alimentations", "theme" : [{"mot":"lait", "description":"Liquide opaque et très nutritif."}, {"mot":"pain", "description":"Aliment fait de farine, d\'eau, de sel et de levain, pétri, levé et cuit au four."}, {"mot":"oeuf", "description":"Corps dur et arrondi."}, {"mot":"viande", "description":"A deux types: blanche et rouge."}, {"mot":"chocolat", "description":"Beacoup utilisé dans la pâtisserie."}, {"mot":"miel", "description":"Substance sirupeuse et sucrée, de couleur ambrée."}, {"mot":"crêpe", "description":"faite d\'une pâte liquide composée de lait, de farine et d\'œufs, frite à la poêle."}, {"mot":"confiture", "description":"pour conserver les fruits."}, {"mot":"huile", "description":"Liquide gras et inflammable."}, {"mot":"dessert", "description":"servis après le fromage (en France)."}]}';

const gestesMouvementsJSON = 
'{"intitule": "Gestes et Mouvements", "theme" : [{"mot":"ouvrir", "description":""}, {"mot":"promener", "description":""}, {"mot":"monter", "description":""}, {"mot":"descendre", "description":""}, {"mot":"accompagner", "description":""}, {"mot":"frapper", "description":""}, {"mot":"imiter", "description":""}, {"mot":"bouger", "description":""}, {"mot":"maladroit", "description":""}, {"mot":"continuellement", "description":""}]}';